const PARTNERS_APPEARANCE = {
	SET_VALUE: "PARTNERS_APPEARANCE___SET_VALUE",
	INCREMENT_CURRENT: "PARTNERS_APPEARANCE___INCREMENT_CURRENT",
	DECREMENT_CURRENT: "PARTNERS_APPEARANCE___DECREMENT_CURRENT",
	SET_VIEWED: "PARTNERS_APPEARANCE___SET_VIEWED",
	START: "PARTNERS_APPEARANCE___START",
	FINISH: "PARTNERS_APPEARANCE___FINISH",
}

const MY_APPEARANCE = {
	SET_VALUE: "MY_APPEARANCE___SET_VALUE",
	INCREMENT_CURRENT: "MY_APPEARANCE___INCREMENT_CURRENT",
	DECREMENT_CURRENT: "MY_APPEARANCE___DECREMENT_CURRENT",
	SET_VIEWED: "MY_APPEARANCE___SET_VIEWED",
	START: "MY_APPEARANCE___START",
	FINISH: "MY_APPEARANCE___FINISH",
}

const ABOUT_PARTNER = {
	SET_VALUE: "ABOUT_PARTNER___SET_VALUE",
	INCREMENT_CURRENT: "ABOUT_PARTNER___INCREMENT_CURRENT",
	DECREMENT_CURRENT: "ABOUT_PARTNER___DECREMENT_CURRENT",
	SET_VIEWED: "ABOUT_PARTNER___SET_VIEWED",
	START: "ABOUT_PARTNER___START",
	FINISH: "ABOUT_PARTNER___FINISH",
}

const ABOUT_ME = {
	SET_VALUE: "ABOUT_ME___SET_VALUE",
	INCREMENT_CURRENT: "ABOUT_ME___INCREMENT_CURRENT",
	DECREMENT_CURRENT: "ABOUT_ME___DECREMENT_CURRENT",
	SET_VIEWED: "ABOUT_ME___SET_VIEWED",
	START: "ABOUT_ME___START",
	FINISH: "ABOUT_ME___FINISH",
}

const PARTNERS_TRAITS = {
	SET_CURRENT: "PARTNERS_TRAITS___SET_CURRENT",
	SET_VALUE: "PARTNERS_TRAITS___SET_VALUE",
	INCREMENT_CURRENT: "PARTNERS_TRAITS___INCREMENT_CURRENT",
	DECREMENT_CURRENT: "PARTNERS_TRAITS___DECREMENT_CURRENT",
	START: "PARTNERS_TRAITS___START",
	FINISH: "PARTNERS_TRAITS___FINISH",
}

const MY_TRAITS = {
	SET_VALUE: "MY_TRAITS___SET_VALUE",
	START: "MY_TRAITS___START",
	FINISH: "MY_TRAITS___FINISH",
}

const TEST = {
	SET_CURRENT: "TEST___SET_CURRENT",
	SET_VALUE: "TEST___SET_VALUE",
	INCREMENT_CURRENT: "TES___INCREMENT_CURRENT",
	DECREMENT_CURRENT: "TES___DECREMENT_CURRENT",
	START: "TEST___START",
	FINISH: "TEST___FINISH",
}

const GLOBAL = {
	CLEAR: "GLOBAL___CLEAR",
	RESET: "GLOBAL___RESET",
	SET_LANGUAGE: "GLOBAL___SET_LANGUAGE",
	START: "GLOBAL___START",
	ADD_IMAGE: "GLOBAL___ADD_IMAGE",
	REMOVE_IMAGE: "GLOBAL___REMOVE_IMAGE"
}

const exp = {
	PARTNERS_APPEARANCE,
	MY_APPEARANCE,
	ABOUT_PARTNER,
	ABOUT_ME,
	PARTNERS_TRAITS,
	MY_TRAITS,
	TEST
};

export default exp;

export {PARTNERS_APPEARANCE, MY_APPEARANCE, ABOUT_PARTNER, ABOUT_ME, PARTNERS_TRAITS, MY_TRAITS, TEST, GLOBAL};